[package]
name = "h1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "set_bencher"
harness = false
